### ISSUE TITLE
Remove unhelpful lint rules

### ISSUE THREAD

**Issue by pveyes** [traveloka/javascript#35]
Some candidates:
 - `prefer-const`
 - `no-else-return`

**Comment by FerdinandAnt** [comment]
Just my thoughts, though :thinking: 
`no-duplicate-imports`

Since we prefer only top-level imports in TVLK5, the following won't be possible without disabling the eslint rule (sample is taken from `@traveloka/explore`)
```jsx
// Notice multiple imports from '@traveloka/explore'
import React from 'react';
import { Request, Response } from 'express';

// --- Utils/const ---
import { TravelokaPageComponent, logger } from '@traveloka/core';
import { fetchViewDescriptionApi, getUTMMediumOfArticle } from '@traveloka/explore';
import { redirect } from '@traveloka/core';

// --- Components ---
import { MobileDetailPage, JSONLDSchemaRenderer } from '@traveloka/explore';
import { MobileExploreHeadMeta } from '../../components/MobileExploreHeadMeta';
```

**Comment by FerdinandAnt** [comment]
`no-unused-expressions`

At least allow some short-circuiting and ternary
(https://eslint.org/docs/rules/no-unused-expressions)

```jsx
// short-circuiting
someCondition && doSomething()

// ternary
.then((err, data) => {
  err ? reject(err) : resolve(data)
})
```

**Comment by pveyes** [comment]
More
 - `react/jsx-handler-names`
 - `no-nested-ternary`
 - `no-param-reassign`

**Comment by FerdinandAnt** [comment]
I'm still in to keep the following, though :thinking: 
- `prefer-const` (cleaner code)
- `no-nested-ternary` (haven't thought about a good example that would benefit this)

**Comment by pveyes** [comment]
Fine let's leave prefer-const for now

**Comment by FerdinandAnt** [comment]
# `no-negated-condition`

**Comment by iamn00b** [comment]
+1 for `react/jsx-handler-names`

**Comment by iamn00b** [comment]
also `default-case` should be a warning instead error, as it is helpful in typescript for exhaustive switch case checking.

I'd love to make PR for this if we have agreed to which rules should be disabled
